# Generated by Django 3.0.5 on 2020-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('type_of_body', models.CharField(choices=[('SE', 'Sedan'), ('MI', 'Micro'), ('CU', 'Compact Utility Vehicle'), ('SU', 'Sport Utility Vehicle'), ('HA', 'Hatchback'), ('MV', 'Minivan'), ('CA', 'Cabriolet'), ('CO', 'Coupe'), ('RO', 'Roadster'), ('SC', 'Sportcar'), ('PU', 'Pickup')], max_length=2)),
            ],
            options={
                'verbose_name': 'The car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
